// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8VDesGFKi6e-zLe4q8hofUgE7vQL2Qf4',
    appId: '1:792593874986:web:2a4510785de10f418d0353',
    messagingSenderId: '792593874986',
    projectId: 'my-app-ef993',
    authDomain: 'my-app-ef993.firebaseapp.com',
    storageBucket: 'my-app-ef993.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaxynWhjHrjmMblTXFyyieBh69fjyH1G8',
    appId: '1:792593874986:android:d75200fece768d5d8d0353',
    messagingSenderId: '792593874986',
    projectId: 'my-app-ef993',
    storageBucket: 'my-app-ef993.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQfpj8BhzInBaeLN6YUqv78BdHE3fceWQ',
    appId: '1:792593874986:ios:3ef20d4874dc44b58d0353',
    messagingSenderId: '792593874986',
    projectId: 'my-app-ef993',
    storageBucket: 'my-app-ef993.appspot.com',
    iosClientId: '792593874986-da0liq356gkmnpql746hj2p1nv8rm1ck.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQfpj8BhzInBaeLN6YUqv78BdHE3fceWQ',
    appId: '1:792593874986:ios:3ef20d4874dc44b58d0353',
    messagingSenderId: '792593874986',
    projectId: 'my-app-ef993',
    storageBucket: 'my-app-ef993.appspot.com',
    iosClientId: '792593874986-da0liq356gkmnpql746hj2p1nv8rm1ck.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );
}
